"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-PayWithLocus',
 'project_name': 'Compute Wallet Rail',
 'track': 'PayWithLocus',
 'pitch': 'A controlled Base payment rail that creates bounded subaccounts for '
          'compute, commerce, and operations while preserving auditable spend '
          'envelopes.',
 'idea_titles': ['Yield-Funded Locus Subaccounts',
                 'Pay-Per-Use Agent Wallets',
                 'Treasury-Controlled Checkout Mesh'],
 'architecture_summary': 'The project creates bounded subaccount payment plans for '
                         'compute, commerce, and operations. A controller contract '
                         'emits spend envelopes and reconciliation receipts while the '
                         'Python side prepares Base/Locus payment bundles ready for '
                         'live credentials.',
 'overlap_targets': ['Bankr Gateway',
                     'Slice',
                     'Celo',
                     'ERC-8004 Receipts',
                     'Lido stETH Treasury',
                     'ENS'],
 'primary_contract_name': 'LocusSpendController',
 'primary_python_module': 'locus_payments',
 'category': 'payments',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'payout_targets',
                       'description': 'Recipient identities and allowlisted routes.'},
                      {'name': 'budget_state',
                       'description': 'Treasury headroom and per-transfer caps.'},
                      {'name': 'payment_route',
                       'description': 'Stablecoin rail and settlement preferences.'},
                      {'name': 'receipts',
                       'description': 'Transfers, confirmations, and reporting '
                                      'artifacts.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for LocusSpendController.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'locus_payments.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'Slice',
               'docs_url': 'https://docs.slice.so/',
               'env_vars': ['SLICE_API_KEY', 'SLICE_HOOK_URL'],
               'endpoint_env': 'SLICE_HOOK_URL',
               'action_kind': 'rest_json',
               'purpose': 'Drive checkout hooks and storefront policy changes.'},
              {'name': 'Celo',
               'docs_url': 'https://docs.celo.org/',
               'env_vars': ['CELO_RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Settle stablecoin-native transfers on Celo rails.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity '
                          'receipts.'}],
 'actions': [{'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 95,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'slice_checkout_hook',
              'target': 'slice',
              'purpose': 'Use Slice for a bounded action in this repo.',
              'partner': 'Slice',
              'action_kind': 'rest_json',
              'max_amount_usd': 35,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Slice only after a dry-run artifact exists.',
                        'Use https://docs.slice.so/ for credential setup.']},
             {'id': 'celo_payment_settle',
              'target': 'celo',
              'purpose': 'Use Celo for a bounded action in this repo.',
              'partner': 'Celo',
              'action_kind': 'contract_call',
              'max_amount_usd': 150,
              'priority': 85,
              'sensitivity': 'low',
              'notes': ['Call Celo only after a dry-run artifact exists.',
                        'Use https://docs.celo.org/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 70,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
